<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />

<material name="brown">
  <color rgba="0.02 0.005 0 1"/>
</material>
<material name="yellow">
  <color rgba="0.6 0.4 0 1"/>
</material>
<material name="black">
  <color rgba="0 0 0 1"/>
</material>

<xacro:property name="base_width" value="0.45" />
<xacro:property name="block_thickness" value="0.05"/>
<xacro:property name="height" value="0.65"/>
<xacro:property name="leg_length" value="0.65"/>
<xacro:property name="backrest_mount_height" value="0.55"/>
<xacro:property name="board_w" value="0.65"/>
<xacro:property name="board_t" value="0.01"/>
<xacro:property name="wheel_radius" value="0.07"/>
<xacro:property name="wheel_thickness" value="0.05"/>
<xacro:property name="wheel_mass" value="0.5"/>
<link name="base_link">
</link>

<link name="base_footprint">
</link>

<joint name="base_footprint_joint" type="fixed">
  <parent link="base_link"/>
  <child link="base_footprint"/>
  <origin xyz="0 0 -${2 * wheel_radius + block_thickness}" rpy="0 0 0"/>
</joint>

<xacro:macro name="side" params="prefix reflect m">
  <link name="${prefix}_side">
      <visual>
          <geometry>
            <box size="${block_thickness} ${block_thickness} ${height}"/>
          </geometry>
          <origin xyz="0 0 ${-height / 6}"/>
          <material name="brown"/>
      </visual>
    <collision>
      <geometry>
        <box size="${block_thickness} ${block_thickness} ${height}"/>
      </geometry>
      <origin xyz="0 0 ${-height / 6}"/>
    </collision>
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12 * (height * height + block_thickness * block_thickness)}" ixy="0.0"
      ixz="0.0" iyy="${m / 12 * (height * height + block_thickness * block_thickness)}" iyz="0.0"
      izz="${m / 12 * 2 * block_thickness * block_thickness}"/>
      <origin xyz="0 0 ${-height / 6}"/>
    </inertial>
  </link>
  <joint name="legging_to_${prefix}_side" type="fixed">
    <parent link="legging"/>
    <child link="${prefix}_side"/>
    <origin xyz="0 ${reflect * (base_width + block_thickness) / 2} 0"/>
  </joint>
</xacro:macro>

<xacro:macro name="leg" params="prefix reflect m">
  <link name="${prefix}_leg">
    <visual>
      <geometry>
        <box size="${leg_length} ${block_thickness} ${block_thickness}"/>
      </geometry>
        <origin xyz="0 0 ${-block_thickness / 2}"/>
        <material name="brown"/>
    </visual>
    <collision>
      <geometry>
        <box size="${leg_length} ${block_thickness} ${block_thickness}"/>
      </geometry>
      <origin xyz="0 0 ${-block_thickness / 2}"/>
    </collision>
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12 * 2 * block_thickness * block_thickness}" ixy="0.0"
      ixz="0.0" iyy="${m / 12 * (leg_length * leg_length + block_thickness * block_thickness)}" iyz="0.0"
      izz="${m / 12 * (leg_length * leg_length + block_thickness * block_thickness)}"/>
      <origin xyz="0 0 ${-block_thickness / 2}"/>
    </inertial>
  </link>
  <joint name="${prefix}_side_to_${prefix}_leg" type="fixed">
    <parent link="${prefix}_side"/>
    <child link="${prefix}_leg"/>
    <origin xyz="0 0 ${-8 * height / 12}"/>
  </joint>
</xacro:macro>

<xacro:macro name="seat_mount" params="prefix reflect m">
  <link name="${prefix}_seat_mount">
    <visual>
      <geometry>
        <box size="${leg_length} ${block_thickness} ${block_thickness}"/>
      </geometry>
      <origin xyz="0 0 ${block_thickness / 2}"/>
      <material name="brown"/>
    </visual>
    <collision>
      <geometry>
        <box size="${leg_length} ${block_thickness} ${block_thickness}"/>
      </geometry>
      <origin xyz="0 0 ${block_thickness / 2}"/>
    </collision>
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12 * 2 * block_thickness * block_thickness}" ixy="0.0"
      ixz="0.0" iyy="${m / 12 * (leg_length * leg_length + block_thickness * block_thickness)}" iyz="0.0"
      izz="${m / 12 * (leg_length * leg_length + block_thickness * block_thickness)}"/>
      <origin xyz="0 0 ${block_thickness / 2}"/>
    </inertial>
  </link>
  <joint name="${prefix}_side_to_${prefix}_seat_mount" type="fixed">
    <parent link="${prefix}_side"/>
    <child link="${prefix}_seat_mount"/>
    <origin xyz="0 0 ${height / 3}"/>
  </joint>
</xacro:macro>

<xacro:macro name="backrest_mount" params="prefix reflect m">
  <link name="${prefix}_backrest_mount">
      <visual>
          <geometry>
            <box size="${block_thickness} ${block_thickness} ${backrest_mount_height}"/>
          </geometry>
          <origin xyz="0 0 ${backrest_mount_height / 2}"/>
          <material name="brown"/>
      </visual>
    <collision>
      <geometry>
        <box size="${block_thickness} ${block_thickness} ${backrest_mount_height}"/>
      </geometry>
      <origin xyz="0 0 ${backrest_mount_height / 2}"/>
    </collision>
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${m / 12 * (block_thickness * block_thickness + backrest_mount_height * backrest_mount_height)}" ixy="0.0"
      ixz="0.0" iyy="${m / 12 * (backrest_mount_height * backrest_mount_height + block_thickness * block_thickness)}" iyz="0.0"
      izz="${m / 12 * 2 * block_thickness * block_thickness}"/>
      <origin xyz="0 0 ${backrest_mount_height / 2}"/>
    </inertial>
  </link>
  <joint name="${prefix}_backrest_mount_to_${prefix}_seat_mount" type="fixed">
    <parent link="${prefix}_seat_mount"/>
    <child link="${prefix}_backrest_mount"/>
    <origin xyz="${-(leg_length - block_thickness) / 2} 0 ${block_thickness}"/>
  </joint>
</xacro:macro>

<xacro:macro name="wheel" params="prefix prefix2 reflect reflect2">
  <link name="${prefix}_${prefix2}_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}" />
      <inertia ixx="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" ixy="0.0" ixz="0.0"
                iyy="${(1/12) * wheel_mass * (3*wheel_radius*wheel_radius + wheel_thickness*wheel_thickness)}" iyz="0.0"
                izz="${(1/2) * wheel_mass * (wheel_radius*wheel_radius)}" />
    </inertial>
  </link>
  <joint name="${prefix}_${prefix2}_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="${prefix}_${prefix2}_wheel"/>
    <axis xyz="0 0 ${reflect2}"/>
    <origin xyz="${reflect * 0.4 * leg_length} ${reflect2 * (base_width + block_thickness) / 2} ${-block_thickness - 0.035}"
    rpy="${-reflect2 * pi/2} 0 0"/>
  </joint>

</xacro:macro>

<xacro:macro name="legging" params="m">
<link name="legging">
  <visual>
    <geometry>
      <box size="${block_thickness} ${base_width} ${block_thickness}"/>
    </geometry>
    <material name="brown"/>
  </visual>
  <collision>
    <geometry>
      <box size="${block_thickness} ${base_width} ${block_thickness}"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="${m}"/>
    <inertia ixx="${m / 12 * (base_width * base_width + block_thickness * block_thickness)}" ixy="0.0"
    ixz="0.0" iyy="${m / 12 * (2 * block_thickness * block_thickness)}" iyz="0.0"
    izz="${m / 12 * (base_width * base_width + block_thickness * block_thickness)}"/>
  </inertial>
</link>

<joint name="base_link_to_legging" type="fixed">
  <parent link="base_link"/>
  <child link="legging"/>
  <origin xyz="0 0 ${8 * height / 12}"/>
</joint>

</xacro:macro>

<xacro:macro name="seat" params="m">
<link name="seat">
  <visual>
    <geometry>
      <box size="${leg_length} ${board_w} ${board_t}"/>
    </geometry>
    <origin xyz="${block_thickness} 0 0"/>
    <material name="yellow"/>
  </visual>
  <collision>
    <geometry>
      <box size="${leg_length} ${board_w} ${board_t}"/>
    </geometry>
    <origin xyz="${block_thickness} 0 0"/>
  </collision>
  <inertial>
    <mass value="${m}"/>
    <inertia ixx="${m / 12 * (board_w * board_w + board_t * board_t)}" ixy="0.0"
    ixz="0.0" iyy="${m / 12 * (leg_length * leg_length + board_t * board_t)}" iyz="0.0"
    izz="${m / 12 * (board_w * board_w + leg_length * leg_length)}"/>
    <origin xyz="${block_thickness} 0 0"/>
  </inertial>
</link>
<joint name="legging_to_seat" type="fixed">
  <parent link="legging"/>
  <child link="seat"/>
  <origin xyz="0 0 ${height / 3 + block_thickness + board_t / 2}"/>
</joint>
</xacro:macro>

<xacro:macro name="backrest" params="m">
<link name="backrest">
  <visual>
    <geometry>
      <box size="${board_t} ${board_w} ${7 * backrest_mount_height / 12}"/>
    </geometry>
    <material name="yellow"/>
  </visual>
  <collision>
    <geometry>
      <box size="${board_t} ${board_w} ${7 * backrest_mount_height / 12}"/>
    </geometry>
  </collision>
  <inertial>
    <mass value="${m}"/>
    <inertia ixx="${m / 12 * (board_w * board_w + 49 * backrest_mount_height * backrest_mount_height / 144)}" ixy="0.0"
    ixz="0.0" iyy="${m / 12 * (49 * backrest_mount_height * backrest_mount_height / 144 + board_t * board_t)}" iyz="0.0"
    izz="${m / 12 * (board_w * board_w + board_t * board_t)}"/>
  </inertial>
</link>
<joint name="legging_to_backrest" type="fixed">
  <parent link="legging"/>
  <child link="backrest"/>
  <origin xyz="-${(leg_length - board_t) / 2 - block_thickness} 0 ${height / 3 + 1.5 * block_thickness + 0.8 * backrest_mount_height}"/>
</joint>
</xacro:macro>

<xacro:legging m="0.1"/>

<xacro:side prefix="right" reflect="1" m="0.5"/>
<xacro:side prefix="left" reflect="-1" m="0.5"/>
<xacro:leg prefix="right" reflect="1" m="0.5"/>
<xacro:leg prefix="left" reflect="-1" m="0.5"/>
<xacro:seat_mount prefix="right" reflect="1" m="0.1"/>
<xacro:seat_mount prefix="left" reflect="-1" m="0.1"/>
<xacro:backrest_mount prefix="right" reflect="1" m="0.1"/>
<xacro:backrest_mount prefix="left" reflect="-1" m="0.1"/>

<xacro:seat m="0.01"/>
<xacro:backrest m="0.01"/>

<xacro:wheel prefix="front" prefix2="right" reflect="1" reflect2="-1"/>
<xacro:wheel prefix="rear" prefix2="right" reflect="-1" reflect2="-1"/>
<xacro:wheel prefix="front" prefix2="left" reflect="1" reflect2="1"/>
<xacro:wheel prefix="rear" prefix2="left" reflect="-1" reflect2="1"/>
</robot>
